version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    command: npm run dev
    networks:
      - app-network

  # Add database service if needed
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: heros_db
  #     POSTGRES_USER: heros_user
  #     POSTGRES_PASSWORD: heros_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 