import type { Metadata } from 'next';
import './globals.css';
import SidebarLayout from './SidebarLayout';
import MirageProvider from '../mirage/MirageProvider';
import { Figtree } from 'next/font/google';

const figtree = Figtree({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`dark ${figtree.className}`} lang="en">
      <body className="bg-background text-foreground">
        <MirageProvider />
        <SidebarLayout>{children}</SidebarLayout>
      </body>
    </html>
  );
}
