import type { Metadata } from "next";
import "./globals.css";
import SidebarLayout from "./SidebarLayout";
import MirageProvider from "../MirageProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="bg-gray-950 text-white min-h-screen">
        <MirageProvider />
        <SidebarLayout>{children}</SidebarLayout>
      </body>
    </html>
  );
}
